version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: metadata-service:latest
    container_name: metadata-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker