spring:
  application:
    name: Metadata-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: metadata-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8081
  address: 0.0.0.0
